In [57]:
# importing
import pandas as pd
import numpy as np

In [58]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [59]:
# reading data
df = pd.read_csv("datasets\Gurgaon\Flats\properties.csv")
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floor_num,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2392,4 BHK Flat in Sector 85 Gurgaon,flat,orris carnation residency,0.90,4531.0,1986.0,Super Built up area 1975(183.48 sq.m.)Built Up...,4,4,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Omaxe Celebration Mall within reach', 'Nearb...",Orris carnation residency is one of gurgaon's ...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4 out of 5', 'Construction4 out of..."
761,2 Bedroom House for sale in Baldev Nagar,house,independent,0.53,5888.0,900.0,Built Up area: 900 (83.61 sq.m.),2,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,NaN,A 2 storeyed residential house is located in b...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1365,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.20,6837.0,1755.0,Super Built up area 1755(163.04 sq.m.)Carpet a...,3,3,3+,not available,"111, Sector 90 Gurgaon, Gurgaon, Haryana",15.0,South-West,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",3 bhk ready to move apartment avaialable on sa...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
1355,4 Bedroom House for sale in Vir Nagar,house,independent,0.78,9725.0,802.0,Carpet area: 802 (74.51 sq.m.),4,4,0,not available,"Veer Nagar, Gurgaon, Haryana, India, Vir Nagar...",3.0,North-East,undefined,"['Lal Superspeciality Hospital', 'Shri Gobind ...","Indipendent house ground floor- Bed room, draw...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2336,3 BHK Flat in Sector 81 Gurgaon,flat,dlf the ultima,2.12,10080.0,2103.0,Super Built up area 2103(195.38 sq.m.)Built Up...,3,3,3+,"pooja room,study room,servant room,others","E-092, Sector 81 Gurgaon, Gurgaon, Haryana",9.0,South,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","Situated in sector 81 gurgaon, dlf the ultima ...","['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [60]:
df.shape

(3961, 20)

In [61]:
# checking duplicates values
df.duplicated().sum()

0

In [62]:
# data summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floor_num        3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [63]:
# checking null values
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floor_num            21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [64]:
df.insert(loc=3,column="sector",value=df.property_name.str.split("in").str.get(1).str.strip().str.replace("Gurgaon","").str.strip().str.lower())

In [65]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floor_num,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,12 Bedroom House for sale in Malibu Town,house,malibu towne,malibu town,8.50,53125.0,1600.0,Built Up area: 1600 (148.64 sq.m.),12,12,3+,not available,"Redwood 14, Malibu Town, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",It's a wholly distinctive home with three open...,"['12 Wardrobe', '12 Fan', '1 Exhaust Fan', '10...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,sector 109,12.00,20000.0,6000.0,Plot area 8000(743.22 sq.m.)Built Up area: 700...,5,6,3,"study room,servant room","H No, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...","Sobha international city, a luxury row houses,...","['5 Wardrobe', '10 Fan', '1 Exhaust Fan', '2 G...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,sector 102,1.28,10534.0,1215.0,Super Built up area 1215(112.88 sq.m.),2,2,3,not available,"Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Check out this 2 bhk apartment for sale in sha...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
3,2 BHK Flat in Sector 99A Gurgaon,flat,conscient habitat,sector 99a,0.27,5599.0,482.0,Carpet area: 484 (44.97 sq.m.),2,2,1,others,"Sector 99A Gurgaon, Gurgaon, Haryana",8.0,South-West,1 to 5 Year Old,NaN,Conscient habitat is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sohna,flat,gls arawali homes,sohna,0.32,6722.0,476.0,Built Up area: 476 (44.22 sq.m.),2,1,0,not available,"Gls Arawali Homes, Sector 4, Gurgaon, Sohna, G...",0.0,NaN,undefined,"['Huda City Centre', 'Golf Course Road', 'Delh...","Property for sale in sector 4, gurgaon. This 2...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction4 out of..."

In [66]:
df.sector.value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
nirvana country                                               53
sector 70                                                     53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sushant lok phase 3                                           16
sector 110                                                    16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 76                                                     14
sector 3                                                      14
sector 53                                                     14
sector 1 imt manesar                                          14
gwal pahari                                                   14
sector 52                                                     14
rajendra park                                                 14
dlf phase 5                                                   14
sector 36a                                                    13
sector 46                                                     13
laxman vihar phase 2                                          13
sector 39                                                     12
sector 50                                                     12
sector 93                                                     12
sector 31                                                     12
sohna road                                                    12
sector 38                                                     12
uppals southend                                               12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 55                                                      9
sector 4                                                       9
ashok vihar phase 2                                            9
south city 1                                                   9
sector 95a                                                     9
mehrauli  road                                                 8
sector 59                                                      8
sector 10a                                                     8
malibu town                                                    8
dwarka expressway                                              8
sector 57                                                      8
c block sushant lok phase 1                                    8
sector 40                                                      8
sector 89 a                                                    8
palam vihar extension                                          8
sector 43                                                      8
new colony                                                     7
sector 36 sohna                                                7
sector 26                                                      7
surat nagar 1                                                  7
sector 11                                                      7
mianwali colony                                                7
sector 51                                                      7
sector 58                                                      7
jacobpura                                                      6
ashok vihar                                                    6
jyoti park                                                     6
sector 5                                                       6
rajiv nagar                                                    6
sector 1                                                       6
sector 30                                                      5
ansal plaza                                                    5
sector 2                                                       5
subhash nagar                                                  5
new palam vihar                                                5
sushant lok phase 2                                            5
sector 9                                                       5
sector 28                                                      5
chakkarpur                                                     5
sector 23a                                                     5
arjun nagar                                                    5
greenwood city                                                 5
manesar                                                        5
dayanand colony                                                5
saraswati vihar                                                5
sector 80                                                      5
sector 105                                                     5
sector 3a                                                      4
suncity                                                        4
sector 12                                                      4
sector 12a                                                     4
bhim nagar                                                     4
new                                                            4
garhi harsaru                                                  4
vishnu garden                                                  4
baldev nagar                                                   4
sector 45                                                      4
madanpuri                                                      4
sector 17                                                      4
surya vihar                                                    4
shivpuri                                                       4
shivaji nagar                                                  4
valley view estate                                             4
sector 6                                                       4
krishna colony                                                 4
imt manesar                                                    4
bhondsi                                                        4
ravi nagar                                                     4
adarsh nagar                                                   4
dharam colony                                                  4
sector 36                                                      4
devilal colony                                                 4
mg road                                                        3
patel nagar                                                    3
laxmi garden                                                   3
sector 110 a                                                   3
b block sushant lok phase 1                                    3
sector 23                                                      3
gandhi nagar                                                   3
sector 17b                                                     3
sector 17a                                                     3
prem nagar                                                     3
maruti kunj                                                    3
sector 8                                                       3
sector 88b                                                     3
a block sushant lok phase 1                                    3
sector 27                                                      3
shakti nagar                                                   3
sector 73                                                      3
sector 15                                                      3
samaspur                                                       2
bhawani enclave                                                2
new palam vihar phase 1                                        2
sector 32                                                      2
nars                                                           2
daulatabad                                                     2
rajiv chowk                                                    2
, delhi ncr                                                    2
sispal vihar                                                   2
golf course ext road                                           2
acharya puri                                                   2
sector 21                                                      2
sohna  road                                                    2
surat nagar phase 2                                            2
pratap nagar                                                   2
mohan nagar                                                    2
sector-11 sohna                                                2
sushant lok                                                    2
sheetla colony                                                 2
golf course road                                               2
hira nagar                                                     2
west rajiv nagar                                               2
rosewood                                                       2
sector 41                                                      2
sector 15 part 2                                               2
lajpat nagar                                                   2
new basti                                                      2
bissar                                                         2
sector 15 part 1                                               2
sector 24                                                      2
shankar vihar                                                  2
iffco chowk                                                    2
farukhnagar                                                    2
new palam vihar phase 2                                        2
ambience island                                                2
mayfield garden                                                2
block a surya vihar                                            2
manohar nagar                                                  2
shanti nagar                                                   2
surat nagar                                                    2
faridabad road                                                 2
sector-2 sohna                                                 2
ashok vihar phase i                                            1
alipur                                                         1
cyber city                                                     1
near euro                                                      1
v block dlf phase 3                                            1
ats marigold                                                   1
saroop garden rajendra park                                    1
hsiidc plot sector 1 imt manesar                               1
devi lal colony gali no 12 gurgaon nr omkar public school      1
dhankot                                                        1
laxman vihar, railway road,                                    1
near pataudi chowk                                             1
rattan garden                                                  1
sector-7 hous                                                  1
ravi nager basai road                                          1
mahalaxmi garden, rajendra place                               1
ansal's palam vihar                                            1
carterpuri village                                             1
civil l                                                        1
block h ashok vihar phase iii extension                        1
gopal nagar, garhi ghasita, sonipat                            1
south city                                                     1
park view                                                      1
lucknow                                                        1
pataudi road                                                   1
mahavir pura                                                   1
sultanpur                                                      1
nirvana country pocket h                                       1
ashok vihar phase 3                                            1
b1 block sector 57                                             1
new colony, sector 7                                           1
khandsa                                                        1
sector-5 sohna                                                 1
part 3 sector 5                                                1
sector 37a                                                     1
sector 4 urban estate                                          1
sadar bazar                                                    1
sector 13                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
anand garden, sector-105                                       1
near khandsa road                                              1
block g sector-57                                              1
sector 42                                                      1
sector 9b                                                      1
om nagar                                                       1
near sector 1 market                                           1
shivji park colony                                             1
udyog vihar phase 1                                            1
tekchand nagar                                                 1
sai kunj                                                       1
new jyoti park                                                 1
old delhi road, opp sector-14                                  1
kheri                                                          1
begampur khatola                                               1
damdma                                                         1
laxmna vihar, phase 2                                          1
sector 5 chowk                                                 1
sector-35 sohna                                                1
bhimgarh kheri phase 3                                         1
bptp                                                           1
near nand hospital                                             1
godrej aria , sector 79 ,                                      1
heritage city                                                  1
naharpur rupa                                                  1
ram nagar                                                      1
urban estate, sector 5                                         1
garauli kalan                                                  1
sector 21a faridabad                                           1
jacobpura near sadar bazar                                     1
jat colony,fazilpur/taj nagar road                             1
huda saraswati vihar                                           1
saraswati enclave                                              1
g block dlf city phase 1                                       1
sector 37b                                                     1
rajiv colony                                                   1
sector 17c                                                     1
sector-5 sheetla colony                                        1
kanahi                                                         1
vir nagar                                                      1
bhora kalan                                                    1
hno 13 sagar enclave sura                                      1
Name: sector, dtype: int64

In [67]:
replacement = {
    'dharam colony':'sector 12','krishna colony':'sector 7','suncity':'sector 54','prem nagar':'sector 13','mg road':'sector 28',
    'gandhi nagar':'sector 28', 'laxmi garden':'sector 11', 'shakti nagar':'sector 11', 'baldev nagar':'sector 7',
    'shivpuri':'sector 7', 'garhi harsaru':'sector 17', 'imt manesar':'manesar', 'adarsh nagar':'sector 12','bhim nagar':'sector 6',
    'shivaji nagar':'sector 11', 'madanpuri':'sector 7', 'saraswati vihar':'sector 28', 'arjun nagar':'sector 8',
    'ravi nagar':'sector 9', 'vishnu garden':'sector 105', 'bhondsi':'sector 11', 'surya vihar':'sector 21',
    'devilal colony':'sector 9', 'valley view estate':'gwal pahari', 'mehrauli  road':'sector 14', 'jyoti park':'sector 7',
    'ansal plaza':'sector 23', 'dayanand colony':'sector 6', 'sushant lok phase 2':'sector 55', 'chakkarpur':'sector 28',
    'greenwood city':'sector 45', 'subhash nagar':'sector 12', 'sohna road road':'sohna road', 'malibu town':'sector 47',
    'surat nagar 1':'sector 104', 'new colony':'sector 7', 'mianwali colony':'sector 12', 'jacobpura':'sector 12',
    'rajiv nagar':'sector 13', 'ashok vihar':'sector 3', 'dlf phase 1':'sector 26', 'nirvana country':'sector 50',
    'palam vihar':'sector 2', 'dlf phase 2':'sector 25', 'sushant lok phase 1':'sector 43', 'laxman vihar':'sector 4',
    'dlf phase 4':'sector 28', 'dlf phase 3':'sector 24', 'sushant lok phase 3':'sector 57', 'dlf phase 5':'sector 43',
    'rajendra park':'sector 105', 'uppals southend':'sector 49', 'sohna':'sohna road', 'ashok vihar phase 3 extension':'sector 5',
    'south city 1':'sector 41', 'ashok vihar phase 2':'sector 5',
}

In [68]:
df.sector.replace(replacement, inplace=True)

In [69]:
a = df.sector.value_counts()[df.sector.value_counts() >=3]
df = df[df['sector'].isin(a.index)]

In [70]:
df['sector'].value_counts()

sohna road                     175
sector 102                     113
sector 85                      110
sector 92                      104
sector 69                       94
sector 65                       90
sector 90                       90
sector 81                       90
sector 109                      88
sector 79                       80
sector 104                      73
sector 83                       69
sector 37d                      68
sector 86                       67
sector 50                       65
sector 107                      60
sector 108                      59
sector 95                       57
sector 56                       57
sector 48                       56
sector 89                       56
sector 2                        55
sector 70a                      54
sector 70                       53
sector 43                       53
sector 37c                      53
sector-33 sohna                 51
sector 84                       51
sector 26                       50
sector 49                       48
sector 67                       48
sector 28                       47
sector 66                       46
sector 103                      45
sector 113                      43
sector 25                       43
sector 82                       42
sector 61                       42
sector 7                        39
sector 106                      38
sector 4                        36
sector 99a                      32
sector 54                       31
sector 12                       30
sector 68                       30
sector 77                       29
sector 72                       29
sector 71                       27
sector 5                        26
sector 57                       24
sector 112                      24
sector 24                       24
sector 105                      23
sector 88a                      23
sector 33                       23
sector 14                       23
sector 67a                      22
sector 111                      22
sector 11                       21
sector 22                       20
sector 3                        20
sector 82a                      20
sector 78                       19
sector 47                       19
sector 74                       18
sector 63a                      18
gwal pahari                     18
sector 91                       17
sector 62                       17
sector 110                      16
sector 99                       16
sector 63                       15
sector 60                       15
sector 52                       14
sector 76                       14
sector 53                       14
sector 55                       14
sector 1 imt manesar            14
sector 6                        13
sector 46                       13
laxman vihar phase 2            13
sector 9                        13
sector 36a                      13
sector 39                       12
sector 38                       12
sector 31                       12
sector 93                       12
sector 9a                       11
sector 41                       11
sector 1a imt manesar           10
sector 13                       10
sector 95a                       9
sector 45                        9
manesar                          9
sector 17                        8
sector 89 a                      8
sector 23                        8
dwarka expressway                8
c block sushant lok phase 1      8
sector 40                        8
sector 8                         8
sector 10a                       8
palam vihar extension            8
sector 59                        8
sector 36 sohna                  7
sector 58                        7
sector 51                        7
sector 1                         6
sector 21                        6
new palam vihar                  5
sector 80                        5
sector 23a                       5
sector 30                        5
sector 36                        4
sector 3a                        4
sector 12a                       4
new                              4
sector 88b                       3
maruti kunj                      3
b block sushant lok phase 1      3
sector 27                        3
sector 110 a                     3
sector 17b                       3
sector 73                        3
sector 15                        3
patel nagar                      3
a block sushant lok phase 1      3
sector 17a                       3
Name: sector, dtype: int64

In [71]:
replace= {
    'sector 95a':'sector 95', 'sector 23a':'sector 23', 'sector 12a':'sector 12', 'sector 3a':'sector 3', 'sector 110 a':'sector 110',
    'patel nagar':'sector 15','a block sector 43':'sector 43','maruti kunj':'sector 12','b block sector 43':'sector 43',
    'sector-33 sohna road':'sector 33', 'sector 1 manesar':'manesar', 'sector 4 phase 2':'sector 4', 'sector 1a manesar':'manesar',
    'c block sector 43':'sector 43', 'sector 89 a':'sector 89', 'sector 2 extension':'sector 2', 'sector 36 sohna road':'sector 36'
}

In [72]:
df.sector.replace(replace, inplace=True)

In [73]:
df[df.sector == "new"]

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floor_num,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1147,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1475,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1648,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3766,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [74]:
df.loc[1147,'sector'] = 'sector 76'
df.loc[1475,'sector'] = 'sector 92'
df.loc[3766,'sector'] = 'sector 37'
df.loc[1648,'sector'] = 'sector 90'

In [75]:
df[df.sector == "new"]

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floor_num, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [76]:
df[df['sector'] == 'new sector 2']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floor_num, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [77]:
df.shape

(3803, 21)

In [78]:
df.duplicated().sum()

0

In [79]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floor_num,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,12 Bedroom House for sale in Malibu Town,house,malibu towne,sector 47,8.50,53125.0,1600.0,Built Up area: 1600 (148.64 sq.m.),12,12,3+,not available,"Redwood 14, Malibu Town, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",It's a wholly distinctive home with three open...,"['12 Wardrobe', '12 Fan', '1 Exhaust Fan', '10...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,sector 109,12.00,20000.0,6000.0,Plot area 8000(743.22 sq.m.)Built Up area: 700...,5,6,3,"study room,servant room","H No, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...","Sobha international city, a luxury row houses,...","['5 Wardrobe', '10 Fan', '1 Exhaust Fan', '2 G...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,sector 102,1.28,10534.0,1215.0,Super Built up area 1215(112.88 sq.m.),2,2,3,not available,"Sector 102 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Check out this 2 bhk apartment for sale in sha...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
3,2 BHK Flat in Sector 99A Gurgaon,flat,conscient habitat,sector 99a,0.27,5599.0,482.0,Carpet area: 484 (44.97 sq.m.),2,2,1,others,"Sector 99A Gurgaon, Gurgaon, Haryana",8.0,South-West,1 to 5 Year Old,NaN,Conscient habitat is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sohna,flat,gls arawali homes,sohna road,0.32,6722.0,476.0,Built Up area: 476 (44.22 sq.m.),2,1,0,not available,"Gls Arawali Homes, Sector 4, Gurgaon, Sohna, G...",0.0,NaN,undefined,"['Huda City Centre', 'Golf Course Road', 'Delh...","Property for sale in sector 4, gurgaon. This 2...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction4 out of..."

In [80]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [81]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floor_num,facing,agePossession,nearbyLocations,furnishDetails,features
196,flat,housing board colony,sector 51,0.30,41666.0,72.0,Carpet area: 72 (6.69 sq.m.),1,1,0,study room,0.0,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",NaN,"['Park', 'Visitor Parking']"
129,flat,dlf the ultima,sector 81,2.30,14603.0,1575.0,Super Built up area 2100(195.1 sq.m.)Carpet ar...,3,4,3+,servant room,27.0,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","['3 Wardrobe', '1 Exhaust Fan', '3 Geyser', '4...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."
2614,house,international city by sobha phase 2,sector 109,9.50,26389.0,3600.0,Plot area 400(334.45 sq.m.),7,6,3,"pooja room,study room,servant room",3.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."
3888,flat,raheja vedaanta,sector 108,1.25,5681.0,2200.0,Super Built up area 2200(204.39 sq.m.),3,2,0,not available,0.0,NaN,1 to 5 Year Old,NaN,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian..."
2432,flat,bestech park view sanskruti,sector 92,2.00,8333.0,2400.0,Super Built up area 2475(229.94 sq.m.)Carpet a...,4,5,3+,servant room,12.0,North,1 to 5 Year Old,"['Sapphire 93 Mall', 'Dwarka Expressway', 'NH-...","['3 Wardrobe', '1 Exhaust Fan', '2 Geyser', '1...","['Intercom Facility', 'Lift(s)', 'Maintenance ..."

In [82]:
df.duplicated().sum()

122

In [83]:
df.to_csv('datasets/Gurgaon/Flats/properties_cleaned_v1.csv',index=False)